// 接口定义（商家端）
const api = {
  login: '/auth/login',
  stats: '/merchant/stats',
  shop: '/merchant/shop',
  orders: '/merchant/orders',
  orderDetail: '/merchant/order/detail',
  orderConfirm: '/merchant/order/confirm',
  // 删除订单（店主专属）：2026-10-07 从管理员网页迁来
  orderDelete: '/merchant/order/delete',
  deliveryTestComplete: '/merchant/delivery/test-complete',
  goods: '/merchant/goods',
  goodsUpdate: '/merchant/goods',
  goodsStatus: '/merchant/goods/status',
  goodsCategories: '/merchant/goods/categories',
  goodsStock: '/merchant/goods/stock',
  // 批量录入：一次提交多条新增 / 按条码查商品（扫码识别用）
  goodsBatch: '/merchant/goods/batch',
  goodsByBarcode: '/merchant/goods/by-barcode',
  upload: '/merchant/upload',
  deliveryMonitor: '/merchant/delivery/monitor',
  robots: '/merchant/robots',
  activities: '/merchant/activities',
  activityStatus: '/merchant/activities/status',
  deviceScan: '/merchant/device/scan',
  deviceWxacode: '/merchant/device/wxacode',
  devicePending: '/merchant/device/pending',
  deviceOpenBin: '/merchant/device/open-bin',
  deviceCloseBin: '/merchant/device/close-bin',
  deviceDispatch: '/merchant/device/dispatch',
  // 一车多单：配送批次
  batchList: '/merchant/delivery/batch/list',
  batchDetail: '/merchant/delivery/batch/detail',
  batchDispatch: '/merchant/delivery/batch/dispatch',
  batchOpenBin: '/merchant/device/batch/open-bin',
  batchCloseBin: '/merchant/device/batch/close-bin',
  batchDispatchAll: '/merchant/device/batch/dispatch',
  batchMockDispatch: '/merchant/device/batch/mock-dispatch',
  orderExceptionRetry: '/merchant/order/exception/retry',
  orderExceptionRefund: '/merchant/order/exception/refund',
  orderExceptionList: '/merchant/orders/exception',
  map: '/merchant/map',
  refunds: '/merchant/refunds',
  refundDetail: '/merchant/refund/detail',
  refundHandle: '/merchant/refund/handle',
  cancelRequests: '/merchant/cancel-requests',
  cancelRequestDetail: '/merchant/cancel-request/detail',
  cancelRequestHandle: '/merchant/cancel-request/handle'
}

module.exports = api
